name: Test Release (No Tag)

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-release-creation:
    name: Test GitHub Release Creation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test Release Creation (Dry Run)
      run: |
        echo "Would create release: v0.1.3"
        echo "Title: Release v0.1.3"
        echo "Notes:"
        echo "## Changes"
        echo ""
        echo "See [CHANGELOG.md](CHANGELOG.md) for details."
        echo ""
        echo "## Installation"
        echo ""
        echo "\`\`\`toml"
        echo "[dependencies]"
        echo "custom-tracing-logger = \"v0.1.3\""
        echo "\`\`\`"
        
        # Test if gh CLI works
        gh --version
        
        # Test authentication (without creating release)
        gh auth status
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}